const PDFDocument = require('pdfkit');
const path = require('path');
const fs = require('fs');

class PDFService {
  _formatINR(amount) {
    return `Rs. ${Number(amount).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
  }

  async generateInvoicePDF(invoice) {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const buffers = [];

      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      const primary = '#1A237E';

      // Header background
      doc.rect(0, 0, doc.page.width, 80).fill(primary);

      // Company name
      doc.fillColor('white').fontSize(22).font('Helvetica-Bold')
        .text('Billo Billings', 40, 20);
      doc.fontSize(10).font('Helvetica')
        .text('Wholesale Notebook Management', 40, 48);

      // Invoice title
      doc.fillColor(primary).fontSize(18).font('Helvetica-Bold')
        .text('INVOICE', doc.page.width - 160, 20, { width: 120, align: 'right' });
      doc.fillColor('#555').fontSize(10).font('Helvetica')
        .text(`# ${invoice.invoiceId}`, doc.page.width - 160, 48, { width: 120, align: 'right' });

      // Divider
      doc.moveDown(2);

      const colLeft = 40;
      const colRight = 320;
      const y = 110;

      // Dealer info
      doc.fillColor('#333').fontSize(11).font('Helvetica-Bold').text('Bill To:', colLeft, y);
      doc.fillColor('#555').fontSize(10).font('Helvetica')
        .text(invoice.dealerName, colLeft, y + 16)
        .text(invoice.dealerShop, colLeft, y + 30)
        .text(`Phone: ${invoice.dealerPhone}`, colLeft, y + 44);

      // Invoice details
      doc.fillColor('#333').fontSize(11).font('Helvetica-Bold').text('Invoice Details:', colRight, y);
      doc.fillColor('#555').fontSize(10).font('Helvetica')
        .text(`Date: ${new Date(invoice.createdAt).toLocaleDateString('en-IN')}`, colRight, y + 16)
        .text(`Status: ${invoice.paymentStatus.toUpperCase()}`, colRight, y + 30)
        .text(`Payment: ${invoice.paymentMode}`, colRight, y + 44);

      // Line items table
      const tableTop = y + 90;
      const headers = ['Product', 'Qty', 'Price', 'Disc%', 'Total'];
      const colWidths = [220, 40, 80, 50, 80];
      const colX = [40, 260, 300, 380, 430];

      // Table header
      doc.rect(40, tableTop, doc.page.width - 80, 22).fill('#1A237E');
      doc.fillColor('white').fontSize(9).font('Helvetica-Bold');
      headers.forEach((h, i) => {
        doc.text(h, colX[i], tableTop + 6, { width: colWidths[i], align: i > 0 ? 'right' : 'left' });
      });

      // Table rows
      let rowY = tableTop + 26;
      invoice.lineItems.forEach((item, idx) => {
        const bg = idx % 2 === 0 ? '#F5F6FA' : 'white';
        doc.rect(40, rowY, doc.page.width - 80, 20).fill(bg);
        doc.fillColor('#333').fontSize(9).font('Helvetica');
        doc.text(item.productName, colX[0], rowY + 5, { width: colWidths[0] });
        doc.text(String(item.quantity), colX[1], rowY + 5, { width: colWidths[1], align: 'right' });
        doc.text(this._formatINR(item.unitPrice), colX[2], rowY + 5, { width: colWidths[2], align: 'right' });
        doc.text(`${item.discountPercent}%`, colX[3], rowY + 5, { width: colWidths[3], align: 'right' });
        doc.text(this._formatINR(item.lineTotal), colX[4], rowY + 5, { width: colWidths[4], align: 'right' });
        rowY += 20;
      });

      // Summary box
      const summaryX = doc.page.width - 220;
      rowY += 16;

      const rows = [
        ['Subtotal', invoice.subtotal],
        ['Discount', -invoice.discountTotal],
        [`GST (${invoice.gstRate}%)`, invoice.gstAmount],
      ];

      doc.fontSize(9).font('Helvetica');
      rows.forEach(([label, val]) => {
        doc.fillColor('#555').text(label, summaryX, rowY, { width: 100 });
        doc.fillColor('#333').text(this._formatINR(Math.abs(val)), summaryX + 100, rowY, { width: 80, align: 'right' });
        rowY += 16;
      });

      // Grand total
      doc.rect(summaryX - 10, rowY, 200, 24).fill(primary);
      doc.fillColor('white').fontSize(11).font('Helvetica-Bold')
        .text('TOTAL', summaryX, rowY + 6, { width: 100 })
        .text(this._formatINR(invoice.totalAmount), summaryX + 100, rowY + 6, { width: 80, align: 'right' });

      rowY += 32;
      doc.fillColor('#2E7D32').fontSize(9).font('Helvetica')
        .text(`Amount Paid: ${this._formatINR(invoice.amountPaid)}`, summaryX, rowY);
      rowY += 14;

      if (invoice.amountDue > 0) {
        doc.fillColor('#C62828').text(`Amount Due: ${this._formatINR(invoice.amountDue)}`, summaryX, rowY);
      }

      // Footer
      doc.fillColor('#AAA').fontSize(8).font('Helvetica')
        .text('Generated by Billo Billings', 40, doc.page.height - 40, { align: 'center', width: doc.page.width - 80 });

      doc.end();
    });
  }
}

module.exports = new PDFService();
